databases:
  # Free-tier PostgreSQL database
  - name: database
    plan: free

services:
  # Web Service (your Laravel app)
  - type: web
    name: laravel-app
    env: docker
    dockerfile: Dockerfile
    healthCheckPath: /
    envVars:
      # App
      - key: APP_NAME
        value: "Laravel Real Estate"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      # IMPORTANT: Change this to your app's URL on Render after your first deploy
      - key: APP_URL
        value: https://your-app-name.onrender.com
      - key: APP_KEY
        generateValue: true # Render will generate a value for this

      # Database (Render provides the DATABASE_URL from the service above)
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString

      # Cache and Session
      - key: CACHE_DRIVER
        value: database
      - key: SESSION_DRIVER
        value: database

      # Mail (add your own mail service credentials)
      - key: MAIL_DRIVER
        value: smtp
      - key: MAIL_HOST
        value: smtp.mailtrap.io # Example
      - key: MAIL_PORT
        value: 2525 # Example
      - key: MAIL_USERNAME
        value: # TODO: Add your mail username
      - key: MAIL_PASSWORD
        value: # TODO: Add your mail password
      - key: MAIL_ENCRYPTION
        value: tls # Example
